app = "app-jhmrrrot"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  GITHUB_TOKEN = "adasdsdfdsfsdfsdfsdfsdf"
  OPENAI_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZW1vX3VzZXIiLCJleHAiOjE3MzUwMTkzMzN9.3NwHFaW0k2fyykejF0iicGBvnuknGjBI6dlSAwn_o_o"
  MYSQL_HOST = "code-analysis-db.internal"
  MYSQL_PORT = "3306"
  MYSQL_USER = "codeanalysis"
  MYSQL_PASSWORD = "secret"
  MYSQL_DATABASE = "codeanalysis"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
