"""create history records table

Revision ID: 8c1926493faf
Revises: 
Create Date: 2025-01-21 09:03:07.811538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1926493faf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_records',
    sa.Column('aid', sa.String(length=36), nullable=False, comment='Unique identifier for the analysis record'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='Timestamp when the analysis was performed'),
    sa.Column('repository', sa.String(length=255), nullable=False, comment='GitHub repository name (owner/repo)'),
    sa.Column('commit_hash', sa.String(length=40), nullable=False, comment='Git commit hash'),
    sa.Column('analysis_result', sa.JSON(), nullable=False, comment='Complete analysis results in JSON format'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Analysis status'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Optional notes or feedback'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Last update timestamp'),
    sa.PrimaryKeyConstraint('aid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_records')
    # ### end Alembic commands ###
